# Spring Properties
spring:
  application:
     name: mywallet-service

input:
  user_service: http://USER-SERVICE/user/find/{id}
  balance_service: http://ACCOUNT-SERVICE/account/balance/{id}
  transfer_service: http://ACCOUNT-SERVICE/account/transfer

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port